### ISSUE TITLE
problem with windows compilation: warning: unrecognized command line option '-Wno-incompatible-pointer-types-discards-qualifiers'

### ISSUE THREAD

**Issue by lucas-watteuw** [kdik/godot-speech-to-text#2]
I use windows 10.

I have this warning: warning: unrecognized command line option '-Wno-incompatible-pointer-types-discards-qualifiers'

This warning is supposed to be resolved with a gcc version superior to 7.
My gcc version is 8.1.0.

I hope this 2 screenshot will help.

![Capture1](https://user-images.githubusercontent.com/81231194/201476937-36670053-3509-4e5e-ba95-ef18e036bebc.PNG)

![Capture2](https://user-images.githubusercontent.com/81231194/201476943-85392c77-ca54-441c-ab5d-174504f08427.PNG)

**Comment by kdik** [comment]
Hi! Thanks for bringing this to attention.

The gcc option `-Wno-incompatible-pointer-types-discards-qualifiers` was only added to suppress the warning: `assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]`. However, the warning was not actually suppressed with the option and I somehow overlooked this.

I now switched the option to `-Wno-discarded-qualifiers` in the latest commit and the warning is now suppressed.

Any libraries you built with those warnings are still valid.

For reference, I am also using gcc 8.1.0, in particular:
> gcc.exe (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0
