### ISSUE TITLE
game closes when initializing the plugin for a second time.

### ISSUE THREAD

**Issue by LeviOS31** [kdik/godot-speech-to-text#3]
i have two different scenes that need the text to speech plugin but when i load in the second scene (after coming from the first scene). the second i let go of the speaking button the game freezes and then seems to crash without giving any errors or warnings.

**Comment by kdik** [comment]
Hi, you should only have one instance of the node SpeechToText and reuse it in every scene.

As for your earlier question in the [youtube video](https://www.youtube.com/watch?v=VE1dYAKs1-s):

The easiest way to have two different speech-to-text models in the game would be to have two different speech-to-text plugins. To do so clone this repo and change the MODELDIR in src/stt.c and src/stt-linux.c to something like `#define MODELDIR "addons/speechtotext2/model" `. Then rename the addons/speechtotext directory to addons/speechtotext2. Recompile the plugin by running `make` (or `mingw32-make` on Windows) in the src directory.

Then modify `addons/speechtotext2/plugin.cfg`, `addons/speechtotext2/Plugin.gd`, `addons/speechtotext2/speechtotext.gdnlib`, `addons/speechtotext2/speechtotext.gdns`, `addons/speechtotext2/SpeechToText.gd` to refer to the new plugin naming. Ie.:
![new_plugin_naming](https://user-images.githubusercontent.com/44341911/206866985-21b0f204-d7bb-4876-8421-9e123f652da7.png)

Add the new plugin to your game manually (alongside the assetlib plugin):
![new_structure](https://user-images.githubusercontent.com/44341911/206867044-7ef1adfd-44c0-4ef7-ba42-ead78520f919.png)

Then in Godot enable the new plugin:
![enable_new_plugin](https://user-images.githubusercontent.com/44341911/206867078-55f66cba-86ab-4899-8e2e-b06b13d0d18b.png)

`SpeechToText` node would use one model and `SpeechToText2` node could use another model.

Here's an example structure of a project, where pressing SPACE gives voice recognition using one model and pressing TAB gives voice recognition using another:
![project_overview](https://user-images.githubusercontent.com/44341911/206867161-f4681fa2-b29f-4ca2-9505-a3434557dd1a.png)

I hope this solves your use case! Feel free to ask any questions, though.
