### ISSUE TITLE
exporting a game 

### ISSUE THREAD

**Issue by LeviOS31** [kdik/godot-speech-to-text#4]
i have a problem with exporting the game. when i export the game for windows and i start it when i get to the scene that has the speech to text in it the game just closes like it crashes. i already put the addons/speechtotext/model in both the same map as the exported executable and in the data map that gets exported with the game but none have worked. i also get a error that it cant open the addons file.
![Knipsel](https://user-images.githubusercontent.com/58821386/211320871-59b08036-898d-4541-bddc-a832acfaa881.PNG)
![image](https://user-images.githubusercontent.com/58821386/211321071-eb8bbed2-2a6a-4f4f-ab54-3f1a7f2e913c.png)
![image](https://user-images.githubusercontent.com/58821386/211321380-f30dfd26-c005-465e-998b-efd4b86463b5.png)
both addons directories are filled with what you said was needed even if i deleted one it didnt make a difference

**Comment by LeviOS31** [comment]
also this is what i found in the log file

```
Mono: Log file is: 'C:/Users/levio/AppData/Roaming/Godot/mono/mono_logs/2023-01-09_14.49.20_3516.log'
godot-speech-to-text plugin loaded
ERROR: Condition "_first != nullptr" is true.
   at: ~List (./core/self_list.h:108) - Condition "_first != nullptr" is true.
ERROR: Condition "_first != nullptr" is true.
   at: ~List (./core/self_list.h:108) - Condition "_first != nullptr" is true.
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
   at: cleanup (core/object.cpp:2070) - ObjectDB instances leaked at exit (run with --verbose for details).
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/resource.cpp:417) - Resources still in use at exit (run with --verbose for details).
```

**Comment by LeviOS31** [comment]
i hope the crash has something to do with the plugin in and that i'm not bothering you with some errors that have nothing to do with the plugin

**Comment by kdik** [comment]
Hey, I'm not sure if this is error you are getting is related to this plugin, but try these two things. 

For windows, add these three dlls from the addons/speechtotext/lib/win32 to the root folder of the exported game

<img width="587" alt="dlls_in_export" src="https://user-images.githubusercontent.com/44341911/211416039-1a800b02-8b18-4d77-a70b-e64b3dd971de.PNG">

Also check that the addons folder structure looks like this 

<img width="557" alt="export_structure" src="https://user-images.githubusercontent.com/44341911/211416569-533c438f-fb0e-4483-b2c8-aff48494bed9.PNG">

Let me know if this does or does not help!

**Comment by LeviOS31** [comment]
it worked thank you so much man.
