### ISSUE TITLE
Node type SpeechToText does NOT appear in the Godot engine after importing plug-in

### ISSUE THREAD

**Issue by samhouston1111** [kdik/godot-speech-to-text#6]
Platform Info:
OS Edition:	Windows 10 Home
OS Version:	22H2
OS build:	19045.3448
OS type:	64-bit operating system, x64-based processor
CPU type:	Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz   1.50 GHz
Installed Ram: 	4.00 GB (3.77 GB usable)
Godot: v3.5.2.stable.official [170ba337a]
User experience level: 2 days in Godot

Problem description:

1) I download godot-3.5 speech-to-text-7009ba5cbffa1480202ac1e0bc239ee819d86f95.zip from Godot Asset Library
2) In Godot-->AssetLib-->Import-->I import the file I downloaded above.
3) "Asset "C:/Users/gilga/Downloads/godot-3.5 speech-to-text-7009ba5cbffa1480202ac1e0bc239ee819d86f95" installed successfully!" message is shown.
4) per Github instructions: "Once installed the node type SpeechToText should appear in the Godot engine." 
5) Unfortunately, the node type "SpeechToText" does not appear in the 'Add child node / Create New Node" list of available nodes.

What am I doing wrong?
Thank you for any help.

**Comment by kdik** [comment]
Hi, sorry for a late reply. In case you are still wondering, have you enabled the plugin through project settings? E.g.

![image](https://github.com/kdik/godot-speech-to-text/assets/44341911/252d182d-c8b8-40aa-a9fa-8b604c5f7f81)

**Comment by samhouston1111** [comment]
Thank you for the help.

May I suggest for complete Godot beginners or idiots like myself that we create a checklist?
(If it is update-able by us users, It may make life easier for you also.)

Something like:

Key items:
1) Enable plug-ins in Godot project setting
2) Enable microphone input in Godot
3) Godot Version X.Y.Z

etc.

I don't know how to do this on GIT (I'm a complete beginner there also).

Thanks again for your help.

**Comment by kdik** [comment]
I updated the readme.md file to mention enabling the plugin

I did not write detailed instructions on enabling as I think that should be done in the Godot documentation, as that is the same for all plugins

Let me know if you have more questions!
